<?php
return [
    'names' => [
        'Claudio',
        'Mario',
        'Giovanni',
        'Luca',
        'Paolo',
        'Giuseppe',
        'Gianmarco',
        'Marco',
        'Filippo',
        'Giulio',
        'Giorgio',
        'Salvatore',
        'Simone',
        'Davide',
        'Silvio',
        'Dario',
        'Omar',
        'Nicola',
        'Armando',
        'Elia'
    ],
    'surnames' => [
        'Cironi',
        'Marioldi',
        'Giovanardi',
        'Rossi',
        'Golia',
        'Grimoldi',
        'Albertazzi',
        'Berlusconi',
        'Fini',
        'Tremonti',
        'Bignami',
        'Lotito',
        'Genoni',
        'Caloni',
        'Perotti',
        'Pireni',
        'Palombo',
        'Pesaro',
        'Rosa',
        'Morelli'
    ],
    'addresses' => [
        'Via San Girolamo 23',
        'Via Giolitti 4',
        'Via Parioli 10',
        'Via Malavita 15',
        'Via Bruttissimi 2',
        'Via Mario Marielli 8',
        'Via Giacomo Grigotti 2',
        'Via Ponzio Pilato 56',
        'Via Monte Nevoso 6',
        'Via Del Drago 43',
        'Via Del Vento 65',
        'Via Montessori 69',
        'Via Adige 6',
        'Via Giallini 67',
        'Via Perotti 43',
        'Via Giunone 9',
        'Via Macabra 9',
        'Via Del Fuoco 43',
        'Via Della Seta 57',
        'Via Volta 3'
    ],
];